In [19]:
def main():
    while(1):
        print('1. Create List\n2. Access Element\n3. Modify Element\n4. Append Element\n5. Insert Element\n6. Remove Element\n7. Pop Element\n8. Delete element\n9. Concatenate Lists\n10. Check Member\n11. Length of List\n12. Slicing\n13. Exit')
        choice = int(input("Enter your choice : "))
        if(choice == 1):
            list1 = []
            list2 = ['apple', 'pineapple', 'custardApple']
            print("list1 and list2 Created!\n\n")
        elif(choice == 2):
            index = int(input("Enter Index : "))
            print(f"The Element at index {index} is {list1[index]}\n\n")
        elif(choice == 3):
            index = int(input("Enter Index : "))
            newElem = input("Enter Element : ")
            list1[index] = newElem
            print("Element Updated!\n")
            print(list1)
        elif(choice == 4):
            newElem = input("Enter Element : ")
            list1.append(newElem)
            print("\n")
            print(list1)
            print("\n")
        elif(choice == 5):
            index = int(input("Enter Index : "))
            newElem = input("Enter Element : ")
            list1.insert(index, newElem)
            print("\n")
            print(list1)
            print("\n")
        elif(choice == 6):
            Elem = input("Enter Element : ")
            list1.remove(Elem)
            print("\n")
            print(list1)
            print("\n")
        elif(choice == 7):
            index = int(input("Enter Index : "))
            list1.pop(index)
            print("\n")
            print(list1)
            print("\n")
        elif(choice == 8):
            index = int(input("Enter Index : "))
            del list1[index]
            print("\n")
            print(list1)
            print("\n")
        elif(choice == 9):
            list3 = list1 + list2
            print("\n")
            print(list3)
            print("\n")
        elif(choice == 10):
            Elem = input("Enter Element : ")
            print("\n")
            print(Elem in list1)
            print("\n")
        elif(choice == 11):
            print("\n")
            print(len(list1))
            print("\n")
        elif(choice == 12):
            start = int(input("Enter Start : "))
            stop = int(input("Enter Stop : "))
            step = int(input("Enter Step : "))
            slicedList = list1[start:stop:step]
            print("\n")
            print(slicedList)
            print("\n")
        elif(choice == 13):
            print("Exiting Program!")
            break
if __name__ == '__main__':
    main()
            

1. Create List
2. Access Element
3. Modify Element
4. Append Element
5. Insert Element
6. Remove Element
7. Pop Element
8. Delete element
9. Concatenate Lists
10. Check Member
11. Length of List
12. Slicing
13. Exit
Enter your choice : 1
list1 and list2 Created!


1. Create List
2. Access Element
3. Modify Element
4. Append Element
5. Insert Element
6. Remove Element
7. Pop Element
8. Delete element
9. Concatenate Lists
10. Check Member
11. Length of List
12. Slicing
13. Exit
Enter your choice : 4
Enter Element : dfgbh
['dfgbh']
1. Create List
2. Access Element
3. Modify Element
4. Append Element
5. Insert Element
6. Remove Element
7. Pop Element
8. Delete element
9. Concatenate Lists
10. Check Member
11. Length of List
12. Slicing
13. Exit
Enter your choice : 4
Enter Element : fgh
['dfgbh', 'fgh']
1. Create List
2. Access Element
3. Modify Element
4. Append Element
5. Insert Element
6. Remove Element
7. Pop Element
8. Delete element
9. Concatenate Lists
10. Check Member
11. Length of 

In [4]:
#version check of numpy
import numpy as np
print(np.__version__)

1.24.4


In [20]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

addition = a + b
print(addition)
subtract = a - b
print(subtract)
multiply = a * b
print(multiply)
divide = a/b
print(divide)
mod = a % b
print(mod)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[1 2 3]
 [4 0 2]
 [1 0 0]]


In [17]:
import numpy as np
a = np.array([[10,22,53],[14,15,56],[37,48,19]])
b = np.array([[29,18,17],[16,25,34],[13,12,11]])
addition = np.add(a,b)
print(addition)
subtract = np.subtract(a,b)
print(subtract)
multiply = np.multiply(a,b)
print(multiply)
dot = np.dot(a,b)
print(dot)
mod = np.mod(a,b)
print(mod)
divide = np.divide(a,b)
print(divide)
sqrt = np.sqrt(a)
print(sqrt)
sort = np.sort(a)
print(sort)
mean = np.mean(b)
print(mean)
median = np.median(a)
print(median)
maxnum = np.max(a)
print(maxnum)
minnum = np.min(b)
print(minnum)

[[39 40 70]
 [30 40 90]
 [50 60 30]]
[[-19   4  36]
 [ -2 -10  22]
 [ 24  36   8]]
[[ 290  396  901]
 [ 224  375 1904]
 [ 481  576  209]]
[[1331 1366 1501]
 [1374 1299 1364]
 [2088 2094 2470]]
[[10  4  2]
 [14 15 22]
 [11  0  8]]
[[0.34482759 1.22222222 3.11764706]
 [0.875      0.6        1.64705882]
 [2.84615385 4.         1.72727273]]
[[3.16227766 4.69041576 7.28010989]
 [3.74165739 3.87298335 7.48331477]
 [6.08276253 6.92820323 4.35889894]]
[[10 22 53]
 [14 15 56]
 [19 37 48]]
19.444444444444443
22.0
56
11
