In [8]:
#verification of NUMPY
import numpy as np
print(np.__version__)

1.24.4


In [1]:
#Creating Numpy Array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#Multi Dimension
dimen_0 = np.array(42)
print(dimen_0.ndim)

dimen_1 = np.array([1, 2, 3, 4, 5])
print(dimen_1.ndim)

dimen_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(dimen_2.ndim)

dimen_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(dimen_3.ndim)


0
1
2
3


In [4]:
#data type

arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr1.dtype)

arr2 = np.array([1,2,3,4])
print(arr2.dtype)

#Create an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

#Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

<U6
int64
[b'1' b'2' b'3' b'4']
|S1
[1 2 3]
int32


In [6]:
#copy and view

#COPY
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
print('\n')

#VIEW
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)
print('\n')

#BASE
#The base  attribute refers to the original object.
arr = np.array([1, 2, 3, 4, 5])
A = arr.copy()
B = arr.view()
print(A.base)
print(B.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
#SHAPE OF ARRAY
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [11]:
#RESHAPE ARRAY
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

##4 rows and 2 cols
newarr = arr.reshape(4, 3)
print(newarr)
print('\n')

#1D array with 12 elements to 3D array with 2x2 elements
newarr = arr.reshape(2, 2, -1)
print(newarr)
print('\n')

#converting to 1D array
newarr = arr.reshape(-1)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
#iterating using For Loop
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)
print('\n')

#iteratinmg using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)
print('\n')

#more parameters of nditer
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    #prints with byte as prefix it means it is byte encoded
    #op_dtypes specifies the data types that you want the iterator to operate 
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


1
2
3
4
5
6
7
8


b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [30]:
#join

#Join two 2-D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
print('\n')

#Join two 2-D arrays along rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print('\n')

#Joining Arrays Using Stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print('\n')

#Stacking Along Rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print('\n')

#Stacking Along Columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
print('\n')

#Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


[[1 2 5 6]
 [3 4 7 8]]


[[1 4]
 [2 5]
 [3 6]]


[1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]


[[[1 4]
  [2 5]
  [3 6]]]


In [33]:
#Split

arr = np.array([1, 2, 3, 4, 5, 6])
#splits array in 4 parts
newarr = np.array_split(arr, 4)
print(newarr)
print('\n')

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
#splits in 3 parts
newarr = np.array_split(arr, 3)
print(newarr)
print('\n')

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
#the 2-D array into three 2-D arrays along rows using axis.
newarr = np.array_split(arr, 3, axis=1)
print(newarr)
print('\n')

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
#the 2-D array into three 2-D arrays along rows using hsplit.
newarr = np.hsplit(arr, 3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [35]:
#Search

arr = np.array([1, 2, 3, 4, 5, 4, 4])
#The indexes where the value is 4
x = np.where(arr == 4)
print(x)
print('\n')

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
#The indexes where the values are even
x = np.where(arr%2 == 0)
print(x)
print('\n')

arr = np.array([6, 7, 8, 9])
#The indexes where the value 7 should be inserted
x = np.searchsorted(arr, 7)
print(x)
print('\n')

arr = np.array([6, 7, 8, 9])
#The indexes where the value 7 should be inserted, starting from the right
x = np.searchsorted(arr, 7, side='right')
print(x)
print('\n')

arr = np.array([1, 3, 5, 7])
#The indexes where the values 2, 4, and 6 should be inserted
x = np.searchsorted(arr, [2, 4, 6])
print(x)


(array([3, 5, 6]),)


(array([1, 3, 5, 7]),)


1


2


[1 2 3]


In [36]:
#Sorting
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [37]:
#filter
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]
